"""add 4 columns to therapist table

Revision ID: 01480a35f8d5
Revises: e23fd24ef6fe
Create Date: 2025-05-22 19:15:20.005443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01480a35f8d5'
down_revision = 'e23fd24ef6fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('therapists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialization', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('about', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('therapists', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('rating')
        batch_op.drop_column('about')
        batch_op.drop_column('specialization')

    # ### end Alembic commands ###
