"""add experience column to therapist table

Revision ID: 5827c077fcb2
Revises: 01480a35f8d5
Create Date: 2025-05-22 20:29:16.719588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5827c077fcb2'
down_revision = '01480a35f8d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('therapists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience', sa.Text(), nullable=True))
        batch_op.alter_column('rating',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('therapists', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('experience')

    # ### end Alembic commands ###
