"""Add phone and religion fields to User model

Revision ID: 6bac0db192e3
Revises: fe5a3cd1718d
Create Date: 2025-04-07 17:54:19.070795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bac0db192e3'
down_revision = 'fe5a3cd1718d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('religion', sa.String(length=100), nullable=True))

    with op.batch_alter_table('user_activities', schema=None) as batch_op:
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(false)'))
        batch_op.alter_column('completed_in_time',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(false)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activities', schema=None) as batch_op:
        batch_op.alter_column('completed_in_time',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(false)'))
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(false)'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('religion')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
