"""Added duration, category, and difficulty_level to SubActivity

Revision ID: 7a42a7de2345
Revises: 
Create Date: 2025-01-24 18:25:21.768466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a42a7de2345'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subactivities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('difficulty_level', sa.Enum('easy', 'medium', 'hard', name='difficulty_levels'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subactivities', schema=None) as batch_op:
        batch_op.drop_column('difficulty_level')
        batch_op.drop_column('category')
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
