"""Change column name and adjust nullable

Revision ID: fe5a3cd1718d
Revises: 3c27c6f19b24
Create Date: 2025-01-25 01:29:39.381666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe5a3cd1718d'
down_revision = '3c27c6f19b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activities', schema=None) as batch_op:
       batch_op.alter_column('completed_int_time',
              new_column_name='completed_in_time',
              existing_type=sa.Boolean(),
              nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activities', schema=None) as batch_op:
        batch_op.alter_column('completed_int_time',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(false)'))
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(false)'))

    # ### end Alembic commands ###
